# Generated by Django 3.2.4 on 2021-06-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceSale', models.DecimalField(decimal_places=2, max_digits=12)),
                ('saleOff', models.FloatField()),
                ('numberItem', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
    ]
