# Generated by Django 3.2.4 on 2021-06-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('priceInput', models.DecimalField(decimal_places=2, max_digits=12)),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('numberProduct', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('colorCode', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('descriptionSize', models.TextField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
            ],
            bases=('Product.product',),
        ),
        migrations.AddField(
            model_name='product',
            name='imageP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productimage'),
        ),
        migrations.CreateModel(
            name='Electro',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('producer', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('national', models.CharField(max_length=255)),
                ('colorP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productcolor')),
                ('sizeP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productsize')),
            ],
            bases=('Product.product',),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('typeClothes', models.CharField(max_length=255)),
                ('manufacture', models.CharField(max_length=255)),
                ('colorP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productcolor')),
                ('sizeP', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.productsize')),
            ],
            bases=('Product.product',),
        ),
    ]
