# Generated by Django 3.2.4 on 2021-06-19 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typeProduct', models.CharField(choices=[('1', 'Book'), ('2', 'Clothes'), ('3', 'Electronic')], max_length=10)),
                ('nameProduct', models.CharField(max_length=255)),
                ('picture', models.ImageField(blank=True, upload_to='images/')),
                ('description', models.TextField(max_length=255)),
                ('priceInput', models.DecimalField(decimal_places=2, max_digits=12)),
                ('numberProduct', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('author', models.CharField(max_length=255)),
                ('publisher', models.CharField(max_length=255)),
            ],
            bases=('Product.product',),
        ),
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('typeClothes', models.CharField(max_length=255)),
                ('manufacture', models.CharField(max_length=255)),
            ],
            bases=('Product.product',),
        ),
        migrations.CreateModel(
            name='Electro',
            fields=[
                ('product_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Product.product')),
                ('producer', models.CharField(max_length=255)),
                ('national', models.CharField(max_length=255)),
            ],
            bases=('Product.product',),
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.product')),
            ],
        ),
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=50)),
                ('descriptionSize', models.TextField(max_length=300)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.clothes')),
            ],
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=50)),
                ('colorCode', models.TextField(max_length=300)),
                ('clothes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.clothes')),
                ('eletric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Product.electro')),
            ],
        ),
    ]
