# Generated by Django 3.2.4 on 2021-06-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ammount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='CardATM',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Payment.payment')),
                ('card_id', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
            ],
            bases=('Payment.payment',),
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Payment.payment')),
                ('CodePayment', models.CharField(max_length=100)),
            ],
            bases=('Payment.payment',),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='Payment.payment')),
                ('producerWallet', models.CharField(max_length=100)),
            ],
            bases=('Payment.payment',),
        ),
    ]
