# Generated by Django 3.2.4 on 2021-06-19 04:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
        ('Item', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusCart', models.CharField(choices=[('True', 'active'), ('False', 'inactive')], max_length=100)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.customer')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typePayment', models.CharField(choices=[('1', 'ATM Card'), ('2', 'Wallet'), ('3', 'Cash')], max_length=100)),
                ('ammount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Shippment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateShip', models.DateTimeField(auto_now=True)),
                ('timeDelivery', models.CharField(max_length=100)),
                ('costShippment', models.FloatField()),
                ('typeShippment', models.CharField(choices=[('True', 'Internal Ship'), ('False', 'Global Ship')], max_length=100)),
                ('statusShipping', models.CharField(choices=[('1', 'Chưa giao'), ('2', 'Đang giao')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='CardATM',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchase.payment')),
                ('card_id', models.CharField(max_length=100)),
                ('owner', models.CharField(max_length=100)),
            ],
            bases=('purchase.payment',),
        ),
        migrations.CreateModel(
            name='Cash',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchase.payment')),
                ('CodePayment', models.CharField(max_length=100)),
            ],
            bases=('purchase.payment',),
        ),
        migrations.CreateModel(
            name='GlobalShippment',
            fields=[
                ('shippment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchase.shippment')),
                ('countryReceive', models.CharField(max_length=255)),
            ],
            bases=('purchase.shippment',),
        ),
        migrations.CreateModel(
            name='InternalShippment',
            fields=[
                ('shippment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchase.shippment')),
                ('cityReceive', models.CharField(max_length=255)),
            ],
            bases=('purchase.shippment',),
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('payment_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='purchase.payment')),
                ('producerWallet', models.CharField(max_length=100)),
            ],
            bases=('purchase.payment',),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Customer', models.CharField(max_length=100)),
                ('dateOrder', models.DateTimeField()),
                ('status', models.CharField(choices=[('True', 'Đã xử lý'), ('False', 'Chưa xử lý')], max_length=100)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.cart')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.payment')),
                ('shippment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.shippment')),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.staffsale')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberItem', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.cart')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.item')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase.order')),
            ],
        ),
    ]
