# Generated by Django 3.2.4 on 2021-06-17 11:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Shippment', '0001_initial'),
        ('Item', '0001_initial'),
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statusCart', models.CharField(choices=[('True', 'active'), ('False', 'inactive')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOrder', models.DateTimeField()),
                ('status', models.CharField(choices=[('True', 'Payment'), ('False', 'Not payment')], max_length=100)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.cart')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Payment.payment')),
                ('shippment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Shippment.shippment')),
            ],
        ),
        migrations.CreateModel(
            name='Cart_Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberItem', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.cart')),
                ('items', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Item.item')),
            ],
        ),
    ]
